# This is a basic workflow to help you get started with Actions

name: Integracion y Entrega continua

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # g) Creando  las variables de entorno
    env:
      nombres: "Mayra Joselyn "
      apellidos: "Yaranga Guevara"
      edad: "23"
      version_proyecto: "3.0"
      seccion_clase: "35806"
      nombre_docente: "Manrique Tejada,Gonzalo Alonso"

      user: ${{secrets.USER}}
      password: ${{secrets.PASSWORD}} 

      
      

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      # MI PRIMER STEP
      - name: presentación
        run: |
          echo "Nombres: $nombres"
          echo "Apellidos: $apellidos"
          echo "Edad: $edad"
       # MI SEGUNDO STEP  
      - name: datos generales
        run: echo "carrera de ingeniería de sistemas"
      # MI TERCER STEP impresion de variables  secretas
      - name: variables de entorno secretas
        run: |
          echo "user: ${{ secrets.user }}"
          echo "password: ${{ secrets.password }}"
      #  Creacion de variables abiertas
      - name: variables abiertas
        run: |
          echo "Versión del proyecto: $version_proyecto"
      #  MI 4TO STEP Creacion de variables abiertas diferentes
      - name: variables abiertas diferentes
        run: |
          echo "Seccion de clase: $seccion_clase"
          echo "Nombre del docente : $nombre_docente"

